FROM apache/airflow:2.10.0

USER root
# 필요한 시스템 패키지가 있다면 여기에 추가 (예: gcc, git 등)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
# 필요한 파이썬 라이브러리 미리 설치
RUN pip install --no-cache-dir \
    mojito2 \
    pykrx \
    psycopg2-binary \
    Django \
    pgvector \
    sentence-transformers \
    finance-datareader \
    openai \
