# Generated by Django 5.2.8 on 2025-12-10 10:41

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(db_column='symbol', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '종목 정보',
                'db_table': 'stock_list',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_collection_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('body_embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('impacted_ticker', models.CharField(db_index=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_collection_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('body_embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=4)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='rag.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rag.user')),
            ],
            options={
                'db_table': 'stock_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='rag.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rag.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rag.user')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=0, max_digits=10)),
                ('close', models.DecimalField(decimal_places=0, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('company', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='rag.company')),
            ],
            options={
                'db_table': 'stock_price',
                'ordering': ['-record_time'],
                'constraints': [models.UniqueConstraint(fields=('company', 'record_time'), name='unique_price_per_time')],
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='rag.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='rag.user')),
            ],
            options={
                'db_table': 'stock_holding',
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rag.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='rag.user')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='rag.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='rag.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow')],
            },
        ),
    ]
