# Generated by Django 5.2.8 on 2025-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True, unique=True),
        ),
    ]
