# Generated by Django 5.2.8 on 2025-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='mileage',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='user',
            name='total_return_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
