# Generated by Django 5.2.8 on 2025-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_post_image_user_mileage_user_total_return_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mileage',
            field=models.IntegerField(default=30000000),
        ),
    ]
